In [ ]:
import pandas as pd
import plotly.graph_objects as go

mines = pd.read_csv("./data_combined/Producing Mines.csv")
canada = pd.read_csv("./data_combined/canada_raster_stack (2).csv")

In [18]:
print(mines.shape)
print(mines.columns)
print(mines.isna().mean())
mines.head()

(2045, 25)
Index(['company1', 'company2', 'company3', 'company4', 'company5', 'company6',
       'namemine', 'town', 'province', 'latitude', 'longitude', 'open1',
       'close1', 'open2', 'close2', 'open3', 'close3', 'information',
       'source1', 'source2', 'source3', 'link1', 'link2', 'link3',
       'Commodity'],
      dtype='object')
company1       0.000000
company2       0.558924
company3       0.816626
company4       0.917359
company5       0.983863
company6       0.991687
namemine       0.337408
town           0.278729
province       0.000000
latitude       0.000000
longitude      0.000000
open1          0.000000
close1         0.000000
open2          0.859169
close2         0.859658
open3          0.968704
close3         0.969193
information    0.747677
source1        0.000000
source2        0.000000
source3        0.000000
link1          0.522249
link2          0.784841
link3          0.934474
Commodity      0.000000
dtype: float64

,company1,company2,company3,company4,company5,company6,namemine,town,province,latitude,...,open3,close3,information,source1,source2,source3,link1,link2,link3,Commodity
0,Quebec Copper Corp. Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Quebec,45.263786,...,NaN,NaN,NaN,0,1,0,NaN,NaN,NaN,Silver
1,Quebec Copper Corp. Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Quebec,45.263786,...,NaN,NaN,NaN,0,1,0,NaN,NaN,NaN,Gold
2,Quebec Copper Corp. Ltd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Quebec,45.263786,...,NaN,NaN,NaN,0,1,0,NaN,NaN,NaN,Copper
3,Noland Mines Ltd.,NaN,NaN,NaN,NaN,NaN,Spruce Creek,Atlin,British Columbia,59.382720,...,NaN,NaN,NaN,0,1,1,https://www.mindat.org/feature-6088912.html,https://www.mindat.org/loc-257276.html,https://mrdata.usgs.gov/ardf/show-ardf.php?ard...,Gold
4,Falconbridge Nickel Mines Ltd.,NaN,NaN,NaN,NaN,NaN,Wesfrob (Tasu),Moresby Island,British Columbia,52.758340,...,NaN,NaN,NaN,0,1,1,https://www.mindat.org/loc-26169.html,NaN,NaN,Iron

In [30]:
mines = mines[["province", "longitude", "latitude", "Commodity"]]
mines["province"].value_counts()

province
British Columbia             635
Quebec                       502
Ontario                      338
Manitoba                     111
Nova Scotia                   86
New Brunswick                 81
Saskatchewan                  80
Newfoundland-and-Labrador     66
Yukon                         59
Alberta                       43
Northwest Territories         28
Nunavut                       16
Name: count, dtype: int64

In [21]:
print(canada.shape)
print(canada.columns)
print(canada.isna().mean())
canada.head()

(129056, 38)
Index(['pixel_id', 'col_idx', 'row_idx', 'x_3978', 'y_3978', 'wgs84_long',
       'wgs84_lat', 'SiO2_pct', 'Al2O3_pct', 'Fe2O3_pct', 'MgO_pct', 'CaO_pct',
       'Na2O_pct', 'K2O_pct', 'TiO2_pct', 'P2O5_pct', 'MnO_pct', 'Au_ppb',
       'Cu_ppm', 'Ni_ppm', 'Co_ppm', 'Li_ppm', 'Cr_ppm', 'Zn_ppm', 'Pb_ppm',
       'Mo_ppm', 'As_ppm', 'Th_ppm', 'U_ppm', 'La_ppm', 'Ce_ppm', 'Nd_ppm',
       'Nb_ppm', 'V_ppm', 'W_ppm', 'Vp_100_kms', 'MagSus_SI', 'Density_gcc'],
      dtype='object')
pixel_id       0.0
col_idx        0.0
row_idx        0.0
x_3978         0.0
y_3978         0.0
wgs84_long     0.0
wgs84_lat      0.0
SiO2_pct       0.0
Al2O3_pct      0.0
Fe2O3_pct      0.0
MgO_pct        0.0
CaO_pct        0.0
Na2O_pct       0.0
K2O_pct        0.0
TiO2_pct       0.0
P2O5_pct       0.0
MnO_pct        0.0
Au_ppb         0.0
Cu_ppm         0.0
Ni_ppm         0.0
Co_ppm         0.0
Li_ppm         0.0
Cr_ppm         0.0
Zn_ppm         0.0
Pb_ppm         0.0
Mo_ppm         0.0
As_ppm         0.0
Th_ppm         0.0
U_ppm          0.0
La_ppm         0.0
Ce_ppm         0.0
Nd_ppm         0.0
Nb_ppm         0.0
V_ppm          0.0
W_ppm          0.0
Vp_100_kms     0.0
MagSus_SI      0.0
Density_gcc    0.0
dtype: float64

,pixel_id,col_idx,row_idx,x_3978,y_3978,wgs84_long,wgs84_lat,SiO2_pct,Al2O3_pct,Fe2O3_pct,...,U_ppm,La_ppm,Ce_ppm,Nd_ppm,Nb_ppm,V_ppm,W_ppm,Vp_100_kms,MagSus_SI,Density_gcc
0,0,0,0,-2200000.0,-150000.0,-122.314575,43.402084,56.007236,14.950943,7.421256,...,2.979677,16.642420,30.499666,15.548808,11.527203,162.62779,69.723015,5.875776,0.0,2.781829
1,1,1,0,-2190000.0,-150000.0,-122.205050,43.438564,56.009804,14.950887,7.420017,...,2.979677,16.643389,30.500694,15.547996,11.529756,162.58803,69.723015,5.856782,0.0,2.761706
2,2,2,0,-2180000.0,-150000.0,-122.095345,43.474910,56.012410,14.950828,7.418763,...,2.979677,16.644354,30.501715,15.547183,11.532316,162.54776,69.723015,5.856951,0.0,2.761808
3,3,3,0,-2170000.0,-150000.0,-121.985466,43.511127,56.015050,14.950768,7.417494,...,2.979677,16.645310,30.502728,15.546371,11.534883,162.50700,69.723015,5.857123,0.0,2.761910
4,4,4,0,-2160000.0,-150000.0,-121.875420,43.547210,56.017720,14.950707,7.416213,...,2.979677,16.646254,30.503730,15.545560,11.537449,162.46585,69.723015,5.857298,0.0,2.762014

In [33]:
canada.drop(columns=['pixel_id', 'col_idx', 'row_idx', 'x_3978', 'y_3978'], inplace=True, errors='ignore')

In [34]:
fig = go.Figure()

fig.add_trace(go.Scattermapbox(
    lat=canada["wgs84_lat"],
    lon=canada["wgs84_long"],
    mode="markers",
    opacity=0.2,
    name="canada raster stack data",
))

fig.add_trace(go.Scattermapbox(
    lat=mines["latitude"],
    lon=mines["longitude"],
    mode="markers",
    opacity=0.5,
    name="Mines data",
))

fig.update_layout(
    mapbox=dict(
        style="carto-positron",
        zoom=2.5,
        center=dict(lat=60, lon=-100)
    ),
    margin=dict(l=0, r=0, t=0, b=0)
)
fig.show()

C:\Users\jylis\AppData\Local\Temp\ipykernel_21484\4281422216.py:3: DeprecationWarning: *scattermapbox* is deprecated! Use *scattermap* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/
  fig.add_trace(go.Scattermapbox(
C:\Users\jylis\AppData\Local\Temp\ipykernel_21484\4281422216.py:11: DeprecationWarning: *scattermapbox* is deprecated! Use *scattermap* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/
  fig.add_trace(go.Scattermapbox(

In [61]:
mines_pivoted = (
    mines
    .assign(value=True)
    .pivot_table(
        index=["province", "longitude", "latitude"],
        columns="Commodity",
        values="value",
        fill_value=False,
        aggfunc="any"
    )
    .reset_index()
)
mines_pivoted = mines_pivoted.astype({col: "int8" for col in mines_pivoted.columns if col not in ["province", "longitude", "latitude"]})
mines_pivoted.drop(columns=['examine', 'gq.mines.gouv.qc.ca', 'https:', 'lime', 'documents', 'Aggregate'], inplace=True, errors='ignore')
mines_pivoted

Commodity,province,longitude,latitude,Almandine,Anhydrite,Anorthosite,Antimony,Apatite,Arsenic,Asbestos,...,Tellurium,Thorium,Tin,Titanium,Tremolite,Tungsten,Uranium,Wollastonite,Zinc,Zircon
0,Alberta,-119.259533,54.028620,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Alberta,-119.178389,53.938609,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Alberta,-117.508710,53.093082,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Alberta,-117.460447,53.607195,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Alberta,-117.440770,53.100822,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,Yukon,-130.205000,63.068610,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
929,Yukon,-130.100000,61.416670,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
930,Yukon,-128.878889,60.547778,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
931,Yukon,-114.316667,62.462500,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
932,Yukon,-113.895833,63.187500,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
mines_pivoted.to_csv("./data_combined/mines_pivoted.csv", index=False)

In [ ]:
import geopandas as gpd

mines_pivoted_gdf = gpd.GeoDataFrame(
    mines_pivoted,
    geometry=gpd.points_from_xy(mines_pivoted["longitude"], mines_pivoted["latitude"]),
    crs="EPSG:4326" 
)

canada_gdf = gpd.GeoDataFrame(
    canada,
    geometry=gpd.points_from_xy(canada["wgs84_long"], canada["wgs84_lat"]),
    crs="EPSG:4326"
)

mines_pivoted_gdf = mines_pivoted_gdf.to_crs("EPSG:3978") # distance in meters
canada_gdf = canada_gdf.to_crs("EPSG:3978")

result = mines_pivoted_gdf.sjoin_nearest(canada_gdf, distance_col="distance")
result.drop(columns=['wgs84_long', 'wgs84_lat', 'geometry', 'index_right'], inplace=True, errors="ignore")
result

,province,longitude,latitude,Almandine,Anhydrite,Anorthosite,Antimony,Apatite,Arsenic,Asbestos,...,La_ppm,Ce_ppm,Nd_ppm,Nb_ppm,V_ppm,W_ppm,Vp_100_kms,MagSus_SI,Density_gcc,distance
0,Alberta,-119.259533,54.028620,0,0,0,0,0,0,0,...,426.649170,505.832300,24.026810,15.378661,274.675720,187.341220,6.156535,0.0,2.741558,4126.216957
1,Alberta,-119.178389,53.938609,0,0,0,0,0,0,0,...,40.271633,46.871870,24.538885,21.961147,248.102190,9.442221,6.003050,0.0,2.702220,5133.985334
2,Alberta,-117.508710,53.093082,0,0,0,0,0,0,0,...,37.787730,163.044660,21.692660,32.119230,63.642590,5.209881,5.870413,0.0,2.768604,4514.349402
3,Alberta,-117.460447,53.607195,0,0,0,0,0,0,0,...,705.889470,947.585200,22.464796,32.361004,174.463130,6.325837,5.845066,0.0,2.725312,5616.867574
4,Alberta,-117.440770,53.100822,0,0,0,0,0,0,0,...,37.225580,162.069430,21.672197,31.796474,63.615643,5.274975,5.869416,0.0,2.768550,2372.610509
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928,Yukon,-130.205000,63.068610,0,0,0,0,0,0,0,...,37.829140,66.271490,29.049960,17.803093,134.885530,2.975310,6.318196,0.0,2.849390,2004.331799
929,Yukon,-130.100000,61.416670,0,0,0,0,0,0,0,...,38.369793,75.360245,29.005688,17.176851,158.391460,5.678414,6.361370,0.0,2.855084,3543.364759
930,Yukon,-128.878889,60.547778,0,0,0,0,0,0,0,...,21.443169,43.874878,19.261835,12.125697,166.019010,0.493165,6.383870,0.0,2.874502,3726.308288
931,Yukon,-114.316667,62.462500,0,0,0,0,0,0,0,...,16.422407,25.451374,7.836191,13.861924,73.250220,2.000000,6.450351,0.0,2.917341,4148.203678
932,Yukon,-113.895833,63.187500,0,0,0,0,0,0,0,...,11.116634,19.183876,6.214617,14.980762,74.624260,2.000000,6.179137,0.0,2.790418,5042.713002

In [94]:
# indices of geographic data points that matched to a mine
used_geo_idx = result["index_right"].unique() 

# rows that did not match to a mine within 10km
negative_samples = canada_gdf.loc[~canada_gdf.index.isin(used_geo_idx)].copy()
negative_samples.drop(columns=['geometry'], inplace=True, errors="ignore")
negative_samples.rename(columns={"wgs84_long": "longitude", "wgs84_lat": "latitude"}, inplace=True)
negative_samples.to_csv("./data_combined/unlabeled_samples.csv", index=False)

In [73]:
result_filtered = result[result["distance"] <= 10_000].copy()
result_filtered["distance"].describe()

count     756.000000
mean     3901.597281
std      1421.587582
min        89.204745
25%      2846.048877
50%      4077.413281
75%      4977.150931
max      9073.286753
Name: distance, dtype: float64

In [74]:
result_filtered.to_csv("./data_combined/geo_and_mineral_data.csv", index=False)

In [81]:
df = pd.read_csv("./data_combined/geo_and_mineral_data.csv")
df.head()

,province,longitude,latitude,Almandine,Anhydrite,Anorthosite,Antimony,Apatite,Arsenic,Asbestos,...,La_ppm,Ce_ppm,Nd_ppm,Nb_ppm,V_ppm,W_ppm,Vp_100_kms,MagSus_SI,Density_gcc,distance
0,Alberta,-119.259533,54.028620,0,0,0,0,0,0,0,...,426.649170,505.83230,24.026810,15.378661,274.675720,187.341220,6.156535,0.0,2.741558,4126.216957
1,Alberta,-119.178389,53.938609,0,0,0,0,0,0,0,...,40.271633,46.87187,24.538885,21.961147,248.102190,9.442221,6.003050,0.0,2.702220,5133.985334
2,Alberta,-117.508710,53.093082,0,0,0,0,0,0,0,...,37.787730,163.04466,21.692660,32.119230,63.642590,5.209881,5.870413,0.0,2.768604,4514.349402
3,Alberta,-117.460447,53.607195,0,0,0,0,0,0,0,...,705.889470,947.58520,22.464796,32.361004,174.463130,6.325837,5.845066,0.0,2.725312,5616.867574
4,Alberta,-117.440770,53.100822,0,0,0,0,0,0,0,...,37.225580,162.06943,21.672197,31.796474,63.615643,5.274975,5.869416,0.0,2.768550,2372.610509

In [82]:
import requests

def get_elevation(lat, lon):
    url = "http://geogratis.gc.ca/services/elevation/cdem/altitude"
    params = {"lat": lat, "lon": lon}
    
    try:
        r = requests.get(url, params=params, timeout=5)
        r.raise_for_status()
        return r.json().get("altitude")
    except Exception:
        return None
    
from time import sleep
from tqdm import tqdm

tqdm.pandas()

def safe_get(row):
    sleep(0.05) 
    return get_elevation(row["latitude"], row["longitude"])

df["elevation"] = df.progress_apply(safe_get, axis=1) # type: ignore

100%|██████████| 756/756 [06:30<00:00,  1.94it/s]

In [98]:
df.to_csv("./data_combined/geo_and_mineral_data.csv", index=False)

In [97]:
df

,province,longitude,latitude,Almandine,Anhydrite,Anorthosite,Antimony,Apatite,Arsenic,Asbestos,...,Ce_ppm,Nd_ppm,Nb_ppm,V_ppm,W_ppm,Vp_100_kms,MagSus_SI,Density_gcc,distance,elevation
0,Alberta,-119.259533,54.028620,0,0,0,0,0,0,0,...,505.832300,24.026810,15.378661,274.675720,187.341220,6.156535,0.0,2.741558,4126.216957,1526.0
1,Alberta,-119.178389,53.938609,0,0,0,0,0,0,0,...,46.871870,24.538885,21.961147,248.102190,9.442221,6.003050,0.0,2.702220,5133.985334,997.0
2,Alberta,-117.508710,53.093082,0,0,0,0,0,0,0,...,163.044660,21.692660,32.119230,63.642590,5.209881,5.870413,0.0,2.768604,4514.349402,1757.0
3,Alberta,-117.460447,53.607195,0,0,0,0,0,0,0,...,947.585200,22.464796,32.361004,174.463130,6.325837,5.845066,0.0,2.725312,5616.867574,1444.0
4,Alberta,-117.440770,53.100822,0,0,0,0,0,0,0,...,162.069430,21.672197,31.796474,63.615643,5.274975,5.869416,0.0,2.768550,2372.610509,1704.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,Yukon,-130.205000,63.068610,0,0,0,0,0,0,0,...,66.271490,29.049960,17.803093,134.885530,2.975310,6.318196,0.0,2.849390,2004.331799,1323.0
752,Yukon,-130.100000,61.416670,0,0,0,0,0,0,0,...,75.360245,29.005688,17.176851,158.391460,5.678414,6.361370,0.0,2.855084,3543.364759,1343.0
753,Yukon,-128.878889,60.547778,0,0,0,0,0,0,0,...,43.874878,19.261835,12.125697,166.019010,0.493165,6.383870,0.0,2.874502,3726.308288,1304.0
754,Yukon,-114.316667,62.462500,0,0,0,0,0,0,0,...,25.451374,7.836191,13.861924,73.250220,2.000000,6.450351,0.0,2.917341,4148.203678,177.0
755,Yukon,-113.895833,63.187500,0,0,0,0,0,0,0,...,19.183876,6.214617,14.980762,74.624260,2.000000,6.179137,0.0,2.790418,5042.713002,308.0

In [99]:
df.columns.to_list()

['province',
 'longitude',
 'latitude',
 'Almandine',
 'Anhydrite',
 'Anorthosite',
 'Antimony',
 'Apatite',
 'Arsenic',
 'Asbestos',
 'Barite',
 'Barium',
 'Be',
 'Bentonite',
 'Beryllium',
 'Bismuth',
 'Building Stone',
 'Cadmium',
 'Caesium',
 'Calcium Carbonate',
 'Cesium',
 'Chromium',
 'Chrysotile',
 'Clay',
 'Closed between 2020 and 2021',
 'Coal',
 'Cobalt',
 'Copper',
 'Diamond',
 'Diatomite',
 'Dimension Stone',
 'Dolomite',
 'Feldspar',
 'Fireclay',
 'Flagstone',
 'Fluorine',
 'Fluorspar',
 'Fullers Earth',
 'GM68420',
 'GM68420.pdf',
 'Gallium',
 'Garnet',
 'Gemstones',
 'Germanium',
 'Gold',
 'Gold Silver',
 'Granite',
 'Graphite',
 'Gypsum',
 'Ilmenite',
 'Iron',
 'Iron ore',
 'Jade',
 'Lead',
 'Lime',
 'Limestone',
 'Lithium',
 'Magnesia',
 'Magnesitic Dolomite',
 'Magnesium',
 'Magnetite',
 'Mercury',
 'Mica',
 'Molybdenum',
 'Nepheline Syenite',
 'Nephrite',
 'Nickel',
 'Niobium',
 'PM',
 'Palladium',
 'Perlite',
 'Phosphate',
 'Platinum',
 'Potash',
 'Pozzolan',
 'Pumice',
 'Pyrite',
 'Pyrophyllite',
 'Quartz',
 'Radium',
 'Rare Earth Elements (REE)',
 'Rhenium',
 'Salt',
 'Selenium',
 'Serpentine',
 'Shale',
 'Siderite',
 'Silica',
 'Silver',
 'Slate',
 'Slerium',
 'Soapstones',
 'Sodium Sulphate',
 'Steatite',
 'Strontium',
 'Sulfur',
 'Sulphur',
 'Sulphure',
 'Talc',
 'Tantalum',
 'Tellerium',
 'Tellurium',
 'Thorium',
 'Tin',
 'Titanium',
 'Tremolite',
 'Tungsten',
 'Uranium',
 'Wollastonite',
 'Zinc',
 'Zircon',
 'geometry',
 'index_right',
 'SiO2_pct',
 'Al2O3_pct',
 'Fe2O3_pct',
 'MgO_pct',
 'CaO_pct',
 'Na2O_pct',
 'K2O_pct',
 'TiO2_pct',
 'P2O5_pct',
 'MnO_pct',
 'Au_ppb',
 'Cu_ppm',
 'Ni_ppm',
 'Co_ppm',
 'Li_ppm',
 'Cr_ppm',
 'Zn_ppm',
 'Pb_ppm',
 'Mo_ppm',
 'As_ppm',
 'Th_ppm',
 'U_ppm',
 'La_ppm',
 'Ce_ppm',
 'Nd_ppm',
 'Nb_ppm',
 'V_ppm',
 'W_ppm',
 'Vp_100_kms',
 'MagSus_SI',
 'Density_gcc',
 'distance',
 'elevation']

In [123]:
cols = ['province',
 'longitude',
 'latitude',
 'Vp_100_kms',
 'MagSus_SI',
 'Density_gcc',
 'elevation',
 'SiO2_pct',
 'Al2O3_pct',
 'Fe2O3_pct',
 'MgO_pct',
 'CaO_pct',
 'Na2O_pct',
 'K2O_pct',
 'TiO2_pct',
 'P2O5_pct',
 'MnO_pct',
 'Au_ppb',
 'Cu_ppm',
 'Ni_ppm',
 'Co_ppm',
 'Li_ppm',
 'Cr_ppm',
 'Zn_ppm',
 'Pb_ppm',
 'Mo_ppm',
 'As_ppm',
 'Th_ppm',
 'U_ppm',
 'La_ppm',
 'Ce_ppm',
 'Nd_ppm',
 'Nb_ppm',
 'V_ppm',
 'W_ppm',
 'Cobalt',
 'Copper',
 'Diamond',
 'Gold',
 'Graphite',
 'Lithium',
 'Nickel',
 'Rare Earth Elements (REE)',
 'Silver',
 'Uranium',]

df_trimmed = df[cols].copy()
df_trimmed

,province,longitude,latitude,Vp_100_kms,MagSus_SI,Density_gcc,elevation,SiO2_pct,Al2O3_pct,Fe2O3_pct,...,Cobalt,Copper,Diamond,Gold,Graphite,Lithium,Nickel,Rare Earth Elements (REE),Silver,Uranium
0,Alberta,-119.259533,54.028620,6.156535,0.0,2.741558,1526.0,10.080060,1.344176,0.915702,...,0,0,0,0,0,0,0,0,0,0
1,Alberta,-119.178389,53.938609,6.003050,0.0,2.702220,997.0,10.509113,1.494849,1.472888,...,0,0,0,0,0,0,0,0,0,0
2,Alberta,-117.508710,53.093082,5.870413,0.0,2.768604,1757.0,31.763702,5.646134,7.142402,...,0,0,0,0,0,0,0,0,0,0
3,Alberta,-117.460447,53.607195,5.845066,0.0,2.725312,1444.0,19.958529,4.739211,4.412431,...,0,0,0,0,0,0,0,0,0,0
4,Alberta,-117.440770,53.100822,5.869416,0.0,2.768550,1704.0,31.612782,5.622567,7.155939,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,Yukon,-130.205000,63.068610,6.318196,0.0,2.849390,1323.0,52.328007,9.973954,10.316870,...,0,0,0,1,0,0,0,0,0,0
752,Yukon,-130.100000,61.416670,6.361370,0.0,2.855084,1343.0,74.150890,11.980661,2.231535,...,0,1,0,1,0,0,0,0,1,0
753,Yukon,-128.878889,60.547778,6.383870,0.0,2.874502,1304.0,64.922104,12.962157,3.370898,...,0,0,0,0,0,0,0,0,0,0
754,Yukon,-114.316667,62.462500,6.450351,0.0,2.917341,177.0,56.176594,12.670290,10.272123,...,0,0,0,1,0,0,0,0,0,0
755,Yukon,-113.895833,63.187500,6.179137,0.0,2.790418,308.0,53.981140,13.969686,11.190473,...,0,0,0,1,0,0,0,0,0,0

In [124]:
cols = [
    'Cobalt',
    'Copper',
    'Diamond',
    'Gold',
    'Graphite',
    'Lithium',
    'Nickel',
    'Rare Earth Elements (REE)',
    'Silver',
    'Uranium'
]

count = (df_trimmed[cols] == 0).all(axis=1).sum()
print("mines with none of the resources listed:", count)
print("mines with at least one of the resources listed:", len(df_trimmed) - count)
print()

for col in cols:
    print(f"{col}: {(df_trimmed[col] == 1).sum()} positives, {(df_trimmed[col] == 0).sum()} negatives")

mines with none of the resources listed: 233
mines with at least one of the resources listed: 523

Cobalt: 29 positives, 727 negatives
Copper: 253 positives, 503 negatives
Diamond: 7 positives, 749 negatives
Gold: 382 positives, 374 negatives
Graphite: 2 positives, 754 negatives
Lithium: 2 positives, 754 negatives
Nickel: 44 positives, 712 negatives
Rare Earth Elements (REE): 2 positives, 754 negatives
Silver: 252 positives, 504 negatives
Uranium: 19 positives, 737 negatives

In [125]:
df_trimmed.to_csv("./data_cleaned/mines.csv", index=False)